set -g mouse on
set-option -g pane-border-format "[#{pane_index}] running #{pane_current_command} at #{pane_current_path}"

## macos
#set -s set-clipboard on

set -g allow-passthrough on
set -g xterm-keys on
set -ga terminal-overrides '*:KSU'
set -g default-terminal "tmux-256color"
#set -ag terminal-overrides ",xterm-256color:RGB"


setw -g mode-keys vi
if-shell '[[ $(uname) = Darwin ]]' {
    # macOS-specific config here
    set -g default-command "reattach-to-user-namespace -l ${SHELL}"
    set-option -g default-command "reattach-to-user-namespace -l zsh"
    bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
} {
    # Linux config here
    bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
}

bind -n F3 set-option -g mouse \; display-message 'Mouse #{?mouse,on,off}'
bind -n F2 set-option -g pane-border-status 
bind -n F1 set-option -g status 
bind -n F10 source-file ~/.tmux.conf \; display-message 'reloaded config'


# bind -n WheelUpPane if -Ft= "#{mouse_any_flag}" "send -M" "send Up"
# bind -n WheelDownPane if -Ft= "#{mouse_any_flag}" "send -M" "send Down"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -g history-limit 10000

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch pane using Mod-vim keys
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D


# switch windows using alt-nr without prefix
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# switch windows using super + arrow keys without prefix
bind -n S-Left select-window -t -1
bind -n S-Right select-window -t +1
# vim
bind -n S-h select-window -t -1
bind -n S-l select-window -t +1


# don't rename windows automatically
set-option -g allow-rename off
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

# set -g status-right-style 'fg=black bg=yellow'
set -g status-right-style 'fg=yellow'
set -g status-right '%Y-%m-%d %H:%M'
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'
